In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
data = {'Transaction_ID': [1, 2, 3, 4, 5],
        'Quantity': [2, 1, 3, 4, 2],
        'Price_per_item': [10.50, 25.00, 5.75, 12.00, 15.50],
        'Customer_ID': ['C001', 'C002', 'C001', 'C003', 'C002']}

In [4]:
df = pd.DataFrame(data)
df

   Transaction_ID  Quantity  Price_per_item Customer_ID
0               1         2           10.50        C001
1               2         1           25.00        C002
2               3         3            5.75        C001
3               4         4           12.00        C003
4               5         2           15.50        C002

In [6]:
df['total_price'] = df['Quantity']*df['Price_per_item']
df

   Transaction_ID  Quantity  Price_per_item Customer_ID  total_price
0               1         2           10.50        C001        21.00
1               2         1           25.00        C002        25.00
2               3         3            5.75        C001        17.25
3               4         4           12.00        C003        48.00
4               5         2           15.50        C002        31.00

In [8]:
df['Transaction_date'] = pd.to_datetime(['2024-01-23','2024-02-13','2024-07-19','2024-04-29','2024-08-12'])
df

,Transaction_ID,Quantity,Price_per_item,Customer_ID,total_price,Transaction_data,Transaction_date
0,1,2,10.50,C001,21.00,2024-01-23,2024-01-23
1,2,1,25.00,C002,25.00,2024-02-13,2024-02-13
2,3,3,5.75,C001,17.25,2024-07-19,2024-07-19
3,4,4,12.00,C003,48.00,2024-04-29,2024-04-29
4,5,2,15.50,C002,31.00,2024-08-12,2024-08-12

In [10]:
df['Transaction_day'] = df['Transaction_date'].dt.day_of_week
df['Transaction_month'] = df['Transaction_date'].dt.month
df['Transaction_year'] = df['Transaction_date'].dt.year
df

,Transaction_ID,Quantity,Price_per_item,Customer_ID,total_price,Transaction_data,Transaction_date,Transaction_day,Transaction_month,Transaction_year
0,1,2,10.50,C001,21.00,2024-01-23,2024-01-23,1,1,2024
1,2,1,25.00,C002,25.00,2024-02-13,2024-02-13,1,2,2024
2,3,3,5.75,C001,17.25,2024-07-19,2024-07-19,4,7,2024
3,4,4,12.00,C003,48.00,2024-04-29,2024-04-29,0,4,2024
4,5,2,15.50,C002,31.00,2024-08-12,2024-08-12,0,8,2024

In [11]:
df = df.drop(columns=['Transaction_data'])

In [12]:
df

,Transaction_ID,Quantity,Price_per_item,Customer_ID,total_price,Transaction_date,Transaction_day,Transaction_month,Transaction_year
0,1,2,10.50,C001,21.00,2024-01-23,1,1,2024
1,2,1,25.00,C002,25.00,2024-02-13,1,2,2024
2,3,3,5.75,C001,17.25,2024-07-19,4,7,2024
3,4,4,12.00,C003,48.00,2024-04-29,0,4,2024
4,5,2,15.50,C002,31.00,2024-08-12,0,8,2024

In [15]:
df_encoded = pd.get_dummies(df, columns=['Customer_ID'], prefix='Customer', dtype=np.int32)

print( "\n df with one hot endoded customer id")
df_encoded

 df with one hot endoded customer id

,Transaction_ID,Quantity,Price_per_item,total_price,Transaction_date,Transaction_day,Transaction_month,Transaction_year,Customer_C001,Customer_C002,Customer_C003
0,1,2,10.50,21.00,2024-01-23,1,1,2024,1,0,0
1,2,1,25.00,25.00,2024-02-13,1,2,2024,0,1,0
2,3,3,5.75,17.25,2024-07-19,4,7,2024,1,0,0
3,4,4,12.00,48.00,2024-04-29,0,4,2024,0,0,1
4,5,2,15.50,31.00,2024-08-12,0,8,2024,0,1,0